default: &default
  # adapter: sqlite3 変更
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode # 追加

development:
  <<: *default
  # database: db/development.sqlite3 変更
  database: MyApp_development

test:
  <<: *default
  # database: db/test.sqlite3 変更
  database: MyApp_test

# Herokuデプロイ時に再度見直す
production:
#半角スペース２個分の空白を開ける
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5